fpp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import authenticate

urlpatterns = [
    # Examples:
    # url(r'^$', 'fpp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^$', 'fpp.views.home', name='home'),
    url(r'^', include('fpp_archive.urls', namespace="fpp_archive")),
    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url('^', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fpp_archive/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^results/$', views.search_results, name='results'),
    url(r'^contact-us/$', views.contact, name='contact'),
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^verify/$', views.verify_upload, name='verify_upload'),
    url(r'^categories/$', views.categories, name='categories'),
]

fpp_archive/models.py
from django.db import models

# Create your models here.
class Keyword(models.Model):
    keyword = models.CharField(max_length=255)

    def __str__(self):
        return self.keyword

class Category(models.Model):
    category = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.category

class Document(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, blank=True)
    publication = models.CharField(max_length=255, blank=True)
    publication_date = models.CharField(max_length=255, blank=True)
    file = models.FileField(max_length=255, upload_to='documents/%Y/%m/%d/')
    keywords = models.ManyToManyField(Keyword)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.title

fpp_archive/views.py
'''Views for the FPP Archive.'''
import os
import pickle
from smtplib import SMTPException

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import EmailMessage, send_mail

from .whoosh_search import FppIndex
from fpp_archive.models import Document
from fpp_archive.ocrPdf import Converter
from fpp.settings import MEDIA_ROOT, MEDIA_URL
from django.contrib import messages

def home(request):
    '''Render the homepage.'''
    context = {'status': None}
    if request.GET.__contains__('status'):
        context['status'] = request.GET.get('status')

    return render(request, 'fpp_archive/home.html', context)

def categories(request):
    '''Render the FPP categories pages.'''
    return render(request, 'fpp_archive/categories.html')

def search_results(request):
    '''Parse a user query, and return a paginated list of results.'''
    if request.GET.__contains__('q'):
        query = request.GET.get('q')
        fulltext = request.GET.get('fulltext')

        temp_index = FppIndex('indexdir')
        full_results = temp_index.search(query.lower(), fulltext)
        paginator = Paginator(full_results, 12) # Show 12 results per page

        page = request.GET.get('page')
        try:
            results = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver the first page
            page = 1
            results = paginator.page(page)
        except EmptyPage:
            # If page is out of range, deliver the last page of results
            page = paginator.num_pages
            results = paginator.page(page)

        first_doc = int(page) * 12 - 11
        last_doc = int(page) * 12
        if last_doc > int(paginator.count):
            last_doc = paginator.count

        if int(page) - 3 < 0:
            page_range = paginator.page_range[0:5]
        else:
            page_range = paginator.page_range[int(page)-3:int(page)+2]

        print(page_range)

        context = {
            'query':     request.GET.get('q'),
            'results':   results,
            'total':     paginator.count,
            'page_range': page_range,
            'first_doc': first_doc,
            'last_doc':  last_doc,
            'full_text': fulltext
        }
        return render(request, 'fpp_archive/search_results.html', context)
    elif request.GET.__contains__('cat'):
        category = request.GET.get('cat')

        temp_index = FppIndex('indexdir')
        full_results = temp_index.cat_search(category)
        paginator = Paginator(full_results, 12) # Show 12 results per page

        page = request.GET.get('page')
        try:
            results = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver the first page
            page = 1
            results = paginator.page(page)
        except EmptyPage:
            # If page is out of range, deliver the last page of results
            page = paginator.num_pages
            results = paginator.page(page)

        first_doc = int(page) * 12 - 11
        last_doc = int(page) * 12
        if last_doc > int(paginator.count):
            last_doc = paginator.count

        if int(page) - 3 < 0:
            page_range = paginator.page_range[0:5]
        else:
            page_range = paginator.page_range[int(page)-3:int(page)+2]

        print(page_range)

        context = {
            'cat':     request.GET.get('cat'),
            'results':   results,
            'total':     paginator.count,
            'page_range': page_range,
            'first_doc': first_doc,
            'last_doc':  last_doc
        }
        return render(request, 'fpp_archive/search_results.html', context)
    else:
        return HttpResponseRedirect('/')

def contact(request):
    '''Send user message to FPP, redirect to / with success message or
    complain on failure.'''
    if request.method == 'POST':
        subject = '[FPP Archive] Message from %s' % request.POST['name']
        body = 'From:\n{0}\n{1}\n\nMessage:\n{2}'.format(
            request.POST['name'],
            request.POST['email'],
            request.POST['comments']
        )
        from_email = request.POST['email']
        recipient_list = ['bigideamgroup@gmail.com']
        try:
            send_mail(subject,
                      body,
                      from_email,
                      recipient_list,
                      fail_silently=True)
            messages.add_message(request, messages.SUCCESS, 'Message Sucessfully Sent!')
            return HttpResponseRedirect('/')
        except SMTPException:
            messages.add_message(request, messages.ERROR, 'Message Failed To Send!')
            return HttpResponseRedirect('/')
    return HttpResponseRedirect('/')

def upload(request):
    '''Send user-contributed file to FPP, redirect to / with success message
    or complain on failure.'''
    if request.method == 'POST':
        subject = '[FPP Archive] User Contribution'
        body = 'An FPP Archive user submitted the attached file.'
        from_email = 'will@quexxon.net'
        recipient_list = ['bigideamgroup@gmail.com']
        attach = request.FILES['upload']
        email = EmailMessage(subject, body, from_email, recipient_list)
        email.attach(attach.name, attach.read(), attach.content_type)
        try:
            email.send(fail_silently=False)
            messages.add_message(request, messages.SUCCESS, 'Document \
                                 Sucessfully Submited For Review!')
            return HttpResponseRedirect('/')
        except SMTPException:
            messages.add_message(request, messages.SUCCESS, 'Failed To Submit Document!')
            return HttpResponseRedirect('/')
    return HttpResponseRedirect('/')

def verify_upload(request):
    '''Adds and Removes database document queue to search index.'''
    if request.method == 'POST':
        idx = FppIndex('indexdir')
        index_queue_file = MEDIA_ROOT + 'temp/index_queue'
        index_remove_file = MEDIA_ROOT + 'temp/remove_queue'
        try:
            if os.path.isfile(index_queue_file):
                idx.create()
                with open(index_queue_file, 'rb') as temp:
                    index_queue = pickle.load(temp)

                for index in index_queue:

                    instance = Document.objects.get(id=index)
                    keyword_tuples = instance.keywords.values_list()
                    temp_keyword_list = many_to_many_field_iter(keyword_tuples)
                    keyword_list = ""
                    for item in temp_keyword_list:
                        keyword_list += item + ','
                    keyword_list = keyword_list[:-1]
                    category_tuples = instance.categories.values_list()
                    temp_category_list = many_to_many_field_iter(category_tuples)
                    category_list = ""
                    for item in temp_category_list:
                        category_list += item + ','
                    category_list = category_list[:-1]
                    file_path = MEDIA_ROOT + str(instance.file)
                    file_url = MEDIA_URL + str(instance.file)
                    img_path = MEDIA_ROOT + "temp/img/"
                    txt_path = MEDIA_ROOT + "temp/txt/"
                    converter = Converter(file_path, img_path, txt_path)
                    content = converter.convert()
                    idx.add(doc_id=str(index),
                            title=instance.title.lower(),
                            url=file_url,
                            content=content.lower(),
                            author=instance.author.lower(),
                            publication=instance.publication.lower(),
                            pub_date=instance.publication_date.lower(),
                            keyword=keyword_list.lower(),
                            category=category_list.lower())

                os.remove(index_queue_file)
                messages.add_message(request, messages.SUCCESS, 'File Sucessfully Added!')
            else:
                messages.add_message(request, messages.WARNING, 'No files to add.')
        except IOError:
            messages.add_message(request, messages.ERROR, 'Sync Failed!')
            return HttpResponseRedirect('/admin/')
        try:
            if os.path.isfile(index_remove_file):
                idx.create()
                with open(index_remove_file, 'rb') as remove_temp:
                    remove_queue  = pickle.load(remove_temp)

                for index in remove_queue:
                    idx.delete('doc_id', str(index))

                os.remove(index_remove_file)
                messages.add_message(request, messages.SUCCESS, 'Files Sucessfully Removed!')
            else:
                messages.add_message(request, messages.WARNING, 'No files to remove.')
        except IOError:
            messages.add_message(request, messages.ERROR, 'Sync Failed!')
            return HttpResponseRedirect('/admin/')

        return HttpResponseRedirect('/admin/')

    return HttpResponseRedirect('/admin/')


def many_to_many_field_iter(tuple_list):
    '''Yield the second value of each tuple in a list.'''
    for item in tuple_list:
        yield item[1]

fpp_archive/templates/fpp_archive/base.html
{% load staticfiles %}
{% spaceless %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="initial-scale=1.0, width=device-width, height=device-height, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <title>{% block title %}FPP Archive{% endblock %}</title>
        {% block conditional-css %}{% endblock %}
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
        <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:300,400,700' rel='stylesheet' type='text/css'>
        <link href="{% static 'fpp_archive/dist/css/style.min.css' %}" rel="stylesheet" type="text/css">
        <link rel="shortcut icon" href="{% static 'fpp_archive/img/logo/favicon.ico' %}" />
        <link rel="apple-touch-icon-precomposed" href="{% static 'fpp_archive/img/logo/ios_bookmark.png' %}"/>
    </head>
    <body>
        <header itemscope itemtype="https://schema.org/WebSite">
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <p class="status-message success"><i class="fa fa-times-circle"></i>{{ message }}</p>
                    {% elif message.tags == 'error' %}
                    <p class="status-message failure"><i class="fa fa-times-circle"></i>{{ message }}</p>
                    {% endif %}
                {% endfor %}
            {% endif %}

            <p itemprop="about">Publishing and Distributing Works Of Enduring And Historic Significance</p>
            <a href="/" target="_self"><img class="logo"src="{% static 'fpp_archive/img/logo/logo.png' %}"></a>
            <nav class="menu site-width plain-link title-font">
                <ul id="menu">
                    <li><a href="/"><i class="fa fa-home"></i></a></li>
                    <li><a id="mission-link" href="/#menu-marker">Our Mission</a></li>
                    <li><a id="about-link" href="/#menu-marker">About The Archive</a></li>
{#                    <li><a href="/categories">Browse The Archive</a></li>#}
{#                    <li><a href="/#menu-marker">Upload To The Archive</a></li>#}
                    <li><a href="/#menu-marker">Donate</a></li>
                    <li><a href="http://firstprinciplespress.org/newsite/" title="Visit FPP Online" target="_blank">Visit FPP Online</a></li>
                    <li><a href="#contact-form">Contact</a></li>
                    <li><a href="/courses/">FPP Courses</a></li>
                </ul>
            </nav>
        </header>

        {% block pre-search %}{% endblock %}

        {% block search %}
        <div class="search" itemscope>
            <form class="site-width" itemscope action="#" onsubmit="goto_sx();">
                <div>
                    <button><i class="fa fa-search fa-2x">
                        </i> <span style="font-size: 25px">Search the Archive</span>
                    </button>
                </div>
            </form>
        </div>
{#            <div class="contact-button-input">#}
{#                        <button type="submit">Search the Archive</button>#}
{#            </div>#}
        {% endblock %}

        {% block content %}{% endblock %}
        <footer>
            <section class="contact-wrapper">
                <h2 class="site-width">Contact FPP</h2>
                <form id="contact-form" class="site-width" action="/contact-us/" method="post">
                    {% csrf_token %}
                    <div class="line-input">
                        <input class="ui-input-elements" type="text" name="name" id="name" placeholder="your name&hellip;" required />
                        <input class="ui-input-elements" type="email" name="email" id="email" placeholder="your e-mail&hellip;" required />
                    </div>
                    <div class="text-input">
                        <textarea class="ui-input-elements" name="comments" id="comments" columns="25" rows="5" placeholder="your message&hellip;" required></textarea>
                    </div>
                    <div class="contact-button-input">
                        <button type="submit">Send Message <i class="fa fa-arrow-circle-right"></i></button>
                    </div>
                </form>
            </section>
            <section class="sub-footer">
                <h4 class="site-width">FPP Disclaimer</h4>
                <p class="site-width">
                First Principles, Inc, is a 501(c)(3) tax-exempt education organization, which promotes real American history as a key source for understanding the foundations of American law, civil government, and our public institutions.  The FPP Archive is made available to the public for educational purposes only, exercising non-commercial, fair use of the material presented throughout this website.
                </p>
                <hr class="separator">
                <div class="copyright site-width" itemscope itemtype="https://schema.org/WebSite">
                    <span itemprop="copyrightYear">copyright &copy; {% now "Y" %}</span>
                    <span itemprop="copyrightHolder">First Principles Press</span>
                    <span>All Rights Reserved</span>
{#                    <span itemprop="creator">Website by <a class="plain-link" href="http://bigideamediagroup.com/" title="Visit Big Idea Media Group's Site" target="_blank" itemscope itemtype="https://schema.org/Organization" itemprop="name">Big Idea Media Group</a></span>#}
                </div>
            </section>
        </footer>
        <script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
        <script src="{% static 'fpp_archive/js/jquery.slicknav.min.js' %}"></script>
        {% block conditional-js %}{% endblock %}
        <script>
            $(function(){
                $('#menu').slicknav();
            });
        </script>
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                <script>
                    $("p.status-message .fa").click(function(){
                        $("p.status-message").addClass("hidden");
                    });
                </script>
                {% elif message.tags == 'error' %}
                <script>
                    $("p.status-message .fa").click(function(){
                        $("p.status-message").addClass("hidden");
                    });
                </script>
                {% endif %}
            {% endfor %}
        {% endif %}
    </body>
</html>
{% endspaceless %}

<script language="JavaScript">
    function goto_sx() {
        var win = window.open('http://sx.fpparchive.org', '_blank');
        win.focus();
    }
</script>

fpp_archive/templates/fpp_archive/home.html
{% extends "fpp_archive/base.html" %}
{% load staticfiles %}
{% block conditional-css %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
{% endblock %}

{% block conditional-js %}
{# Imports #}
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<script src="{% static 'fpp_archive/js/unslider.min.js' %}"></script>
<script src="{% static 'fpp_archive/js/uploadbtn.min.js' %}"></script>
<script src="{% static 'fpp_archive/js/tabtoaccordion.min.js' %}"></script>
{# Scripts #}
<script>
    $(function() { $( "#tabs" ).tabs(); });
</script>

<script>
    $(document).ready(function(){$(".slider .banner .slider-img").css("display", "block");var unslider=jQuery('.banner').unslider({fluid:true,speed:1000,delay:5000});jQuery('.unslider-arrow').click(function(){console.log('asdf');var fn=this.className.split(' ')[1];unslider.data('unslider')[fn]();});});
</script>

<script>
    $(document).ready(function(){
        $(window).resize(function(e){ updateUI(); }); updateUI();
    });
</script>
{% endblock %}

{% block pre-search %}
<div class="slider">

    <div class="banner">
	    <div id="slider-nav">
		    <a href="#" class="unslider-arrow prev"><i class="fa fa-chevron-left fa-3x"></i></a>
			<a href="#" class="unslider-arrow next"><i class="fa fa-chevron-right fa-3x"></i></a>
	    </div>
        <ul>
            <li><img class="slider-img" src="{% static 'fpp_archive/img/slider/slider1.png' %}"></li>
            <li><img class="slider-img" src="{% static 'fpp_archive/img/slider/slider2.png' %}"></li>
            <li><img class="slider-img" src="{% static 'fpp_archive/img/slider/slider3.png' %}"></li>
            <li><img class="slider-img" src="{% static 'fpp_archive/img/slider/slider4.png' %}"></li>
            <li><img class="slider-img" src="{% static 'fpp_archive/img/slider/slider5.png' %}"></li>
        </ul>
    </div>
</div>
{% endblock %}

{% block content %}
<section class="main-content site-width" id="menu-marker">
    <h2>Discover the FPP Archive</h2>
    <div itemscope itemtype="https://schema.org/WebSite" class="tabs" id="tabs">
        <ul>
            <li><a href="#tabs-1">Our Mission</a></li>
            <li><a href="#tabs-2">About the Archive</a></li>
            <li><a href="#tabs-3">Donate to the Project</a></li>
{#            <li><a href="#tabs-4">Contribute to the Archive</a></li>#}
        </ul>
        <div id="tabs-1">
            <div class="tab-content">
                <p>First Principles, Inc. was founded in 1993 to provide historical instructions and information about the truth and current significance of the first principles of america, particularly as they provide the foundation for our institutions emphasizing virtue, honor and patriotism, self-government, individual responsibility, and independent sovereignty, which begins with accountability of each governmental body at the country, state, and national level to We, The People.</p>
                <p>Since its founding, First Principles has been committed to publishing and distributing works of enduring and historic significance, equipping concerned americans to uphold support and defend America's founding and first principles. Through this website, an archive of these materials is made available to the public for the first time.</p>
            </div>
            <div class="tab-img-container">
                <img src="{% static 'fpp_archive/img/tabs/mission.jpg' %}" class="tab-img">
            </div>
            <div class="clear"></div>
        </div>
        <div id="tabs-2" itemprop="about">
            <div class="tab-content">
                <p>After more than 20 years of work, First Principles Press has moved its extensive library archives from filing cabinets to digital, preserving

                it from decay and making it accessible to people across the world through this archive. This resource will serve upcoming scholars who

                have no first-hand knowledge or experience of the threats that were met by faithful patriots to preserve America’s Godly heritage and way

                of life.</p>
                <p>FPP has continually contended for the truth of the Christian foundations of American law and civil government, while exposing an array

                of undemocratic changes carried out too often without media exposure and thus little, if any, citizen review. Contrary to the flawed view of

                history that things just randomly happen or evolve, First Principles has documented in this archive the activities of personal and

                corporate players who have altered the institutions of our Constitutional Republic throughout the 20th Century.

                The FPP Fighting Digital Archive contains more than 15,000 supporting documents and ephemera for FPP’s three national campaigns: The

                American History Restoration Project, “Exemplary Conduct” &amp; Prayer in the U.S. Armed Forces and our sister site on moral virtue

                RSVPAmerica. This Digital Archive Project contains selections from First Principles’ vast collection of historic books, backgrounders,

                research and articles from 1993 to present. We seek to preserve, organize and broaden the influence and availability of First Principles’

                collections for future research, permanent storage and increasing ease of retrieval.</p>
            </div>
        </div>
        <div id="tabs-3">
            <div class="tab-img-container">
                <img src="{% static 'fpp_archive/img/tabs/donate.jpg' %}" class="tab-img">
            </div>
            <div class="tab-content">
                <p>Since 1993, First Principles has stood for the Lord’s righteousness in

                America. It is only by the grace of God and with the prayers and

                support from our generous donors that we are able to continue our

                mission and ministry through the FPP Archive. God has been so

                faithful to provide for the work He has given to FPP. We are very

                grateful for those who have supported this work, and hope you will be

                with us as we continue onward.</p>
                <p>First Principles, Inc. is a 501(c)(3) tax-exempt foundation and gifts to

                First Principles, Inc. are tax deductible to the full extent permitted by

                law.</p>
                <p>**Note: To donate with a PayPal account, simply log in on the next page using your PayPal

                username and password. To donate with a credit card, find “Don’t have a PayPal account? Use

                your credit card or bank account (where available).” on the next page and click “Continue.”</p>
                <form id="donate_form" action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank"><input name="cmd" value="_s-xclick" type="hidden"> <input name="hosted_button_id" value="Y5G8MTGPYK25Q" type="hidden"> <input alt="PayPal - The safer, easier way to pay online!" name="submit" src="https://www.paypal.com/en_US/i/btn/btn_donateCC_LG.gif" type="image"> <img style="display: none ! important;" alt="" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" border="0" height="1" width="1"></form>
            </div>
            <div class="clear"></div>
        </div>
        <div id="tabs-4">
            <div class="tab-content">
                <p>First Principles, Inc. is dedicated to preserving the historical account

                of the events that have shaped our nation. If you have documents,

                photos or articles that you would like to contribute to the FPP Archive

                for the purpose of preserving them for future generations, please

                feel free to upload them here for retreval by a staff member. Fpp will

                review them and if they qualify as historically relelvant, FPP will

                include them along with the name of the contributor on this site.</p>
                <p>Simply use the upload tool below to browse your hard drive and

                upload them. If you have documents or photos that are not currenlty

                in a digital format, you can contact us and we will let you know how

                to to get copies of those documents to our organization.</p>
                <p>Thank you,<br>FPP Staff</p>
                <form action="{% url 'fpp_archive:upload' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="contribute">
                        <div><input id="uploadFile" placeholder="Choose File" disabled="disabled" /></div>
                        <div class="fileUpload contribute-btn">
                            <span>Browse</span>
                            <input type="file" name="upload" class="upload" id="uploadBtn" value="" required accept=".pdf"/>
                        </div>
                        <button type="submit" id="upload-btn" class="contribute-btn">Upload</button>
                    </div>
                </form>
            </div>
            <div class="tab-img-container">
                <img src="{% static 'fpp_archive/img/tabs/contribute.jpg' %}" class="tab-img">
            </div>
            <div class="clear"></div>
        </div>
    </div>
</section>
{% endblock %}

fpp_archive/templates/fpp_archive/search_results.html
{% extends "fpp_archive/base.html" %}
{% load staticfiles %}
{% load fpp_extras %}

{% block pre-search %}<div class="search-results-banner"></div>{% endblock %}

{% block content %}
<section itemscope itemtype="https://schema.org/SearchResultPage" class="search-results site-width">
    <span>Search For: </span><h2>{{ query }}</h2>
    <p>Showing {{ first_doc }}-{{ last_doc }} of {{ total }} Documents</p>
    <hr class="separator">
    <ul>
        {% for result in results %}
        <li>
            <h3><a class="plain-link" href="{{ result.url }}" alt="{{ result.title }}">{{ result.title|title }}</a></h3>
            <dl>
                {% if result.author %}
                <dt>Author:</dt>
                <dd  itemprop="author">{{ result.author|title }}</dd>
                {% endif %}
                {% if result.publication %}
                <dt>Publication:</dt>
                <dd itemprop="citation">{{ result.publication|title }}</dd>
                {% endif %}
                {% if result.category %}
                <dt>Category:</dt>
                <dd itemprop="citation">{{ result.category }}</dd>
                {% endif %}
            </dl>
            {% if result.keyword %}
            <dl class="keywords">
                <dt>Keywords:</dt>
                <dd>{{ result.keyword|keylist:','|safe }}</dd>
            </dl>
            {% endif %}
            <hr class="separator">
        </li>
        {% endfor %}
    </ul>
</section>

<div class="pagination site-width">
    {% if results.has_previous %}
    <a class="plain-link previous-page" href="{% url 'fpp_archive:results' %}?q={{ query }}&page={{ results.previous_page_number }}"><i class="fa fa-arrow-left"></i> Previous</a>
    {% endif %}

    {% if total > 12 %}
    <ul>
        {% for page in page_range %}
        <li><a class="plain-link" href="{% url 'fpp_archive:results' %}?{% if query %}q={{ query }}{% endif %}{% if cat %}cat={{ cat }}{% endif %}&page={{ page }}{% if full_text %}&fulltext=on{% endif %}">{{ page }}</a></li>
        {% endfor %}
    </ul>
    {% endif %}

    {% if results.has_next %}
    <a class="plain-link next-page" href="{% url 'fpp_archive:results' %}?q={{ query }}&page={{ results.next_page_number }}">Next <i class="fa fa-arrow-right"></i></a>
    {% endif %}
</div>
{% endblock %}