courses/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.courses, name='index'),
    url(r'^(?P<course_name>[\w-]+)/$', views.toc, name='toc'),
    url(r'^(?P<course_name>[\w-]+)/(?P<course_day>[0-9]+)/$',
        views.single, name='single'),
    url(r'^(?P<filetype>epub)/(?P<course_name>[\w-]+)/$', views.epub_gen, name='epub'),
    url(r'^auth/register/$', views.register, name='register'),
]

fpp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import authenticate

urlpatterns = [
    # Examples:
    # url(r'^$', 'fpp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^$', 'fpp.views.home', name='home'),
    url(r'^', include('fpp_archive.urls', namespace="fpp_archive")),
    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url('^', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.core.urlresolvers import reverse
from django.utils.text import slugify

# Create your models here.

class Course(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField()
    subtitle = models.TextField()
    banner = models.ImageField(
        upload_to='courses/banners',
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:toc', args=[self.slug])


class Lesson(models.Model):
    title = models.CharField(max_length=255)
    section_number = models.IntegerField()
    day_number = models.IntegerField()
    course = models.ForeignKey(Course)
    content = RichTextField(
        config_name='courses_ckeditor',
    )
    position = models.PositiveSmallIntegerField("Position")

    class Meta:
        ordering = ['position']

    def __str__(self):
        return str(self.section_number) + '.' + str(self.day_number) + ' ' + self.title

courses/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    next = forms.CharField(initial='{{ next }}', widget=forms.HiddenInput)
    class Meta:
        model = User
        fields = ("username", "email")

courses/views.py
from io import BytesIO

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.db.models import Count
from django.conf import settings
#from django.contrib.auth.forms import UserCreationForm
from .forms import RegistrationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

from bs4 import BeautifulSoup
from ebooklib import epub

from .models import Course, Lesson


# Create your views here.
def courses(request):
    '''Render the Request Page.'''
    return render(request, 'courses/index.html')

@login_required
def toc(request, course_name):
    course = get_object_or_404(Course, slug=course_name)
    lessons = course.lesson_set.all()
    sections = lessons.values('section_number')\
        .order_by('section_number')\
        .annotate(total=Count('section_number'))
    lessons_final = []

    index = 0
    old_value = 1
    for section in sections:
        # Calculate the starting and ending day of each section
        start = old_value
        finish = start + (section['total'] - 1)
        solo = True if (finish - start == 0) else False
        old_value = finish + 1

        # Build a list for looping through sections and lessons
        lessons_final.append({})
        lessons_final[index]['section_number'] = section['section_number']
        lessons_final[index]['lessons'] = lessons.filter(section_number=section['section_number'])
        lessons_final[index]['total'] = section['total']
        lessons_final[index]['start'] = start
        lessons_final[index]['finish'] = finish
        lessons_final[index]['solo'] = solo
        index += 1

    context = {
        'course': course,
        'lessons': lessons_final
    }
    return render(request, 'courses/toc.html', context)

@login_required
def single(request, course_name, course_day):
    course = get_object_or_404(Course, slug=course_name)
    lesson = get_object_or_404(Lesson, \
                               course__slug=course_name, \
                               day_number=course_day)
    total_days = course.lesson_set.all().count()
    next_day = (lesson.day_number + 1) if (lesson.day_number < total_days) else False

    context = {
        'course': course,
        'lesson': lesson,
        'next': next_day,
    }
    return render(request, 'courses/single.html', context)

def epub_gen(request, filetype, course_name):
    # Create the HttpResponse object with the appropriate PDF headers.
    response = HttpResponse(content_type='application/epub+zip')
    response['Content-Disposition'] = 'attachment; filename="' + course_name + '.epub"'

    buffer = BytesIO()

    course = get_object_or_404(Course, slug=course_name)
    lessons = course.lesson_set.all()
    sections = lessons.values('section_number') \
        .order_by('section_number') \
        .annotate(total=Count('section_number'))
    sect_list = []

    index = 0
    for section in sections:
        # Build a list for looping through sections and lessons
        sect_list.append({})
        sect_list[index]['section_number'] = section['section_number']
        sect_list[index]['lessons'] = lessons.filter(section_number=section['section_number'])
        index += 1

    book = epub.EpubBook()

    # set metadata
    book.set_identifier('id123456')
    book.set_title(course.title)
    book.set_language('en')

    book.add_author('First Principles Press')
    book.toc = []
    book.spine = ['nav']

    # create chapter
    index = 0
    for section in sect_list:
        book.toc.append([epub.Section('Section ' + str(section['section_number'])), []])
        for lesson in section['lessons']:
            soup = BeautifulSoup(lesson.content, 'html.parser')
            if soup.img:
                soup.img.decompose()
            file_name = 'day_' + str(lesson.day_number) + '.xhtml'
            chapter = epub.EpubHtml(title=lesson.title, file_name=file_name)
            chapter.content = '<h1>' + lesson.title + '</h1>'
            chapter.content += str(soup)
            book.add_item(chapter)
            book.toc[index][1].append(chapter)
            book.spine.append(chapter)
        index += 1

    # add default NCX and Nav file
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())

    # define CSS style
    style = 'BODY {color: white;}'
    nav_css = epub.EpubItem(uid="style_nav", file_name="style/nav.css", media_type="text/css", content=style)

    # add CSS file
    book.add_item(nav_css)

    # write to the file
    epub.write_epub(buffer, book, {})


    # Get the value of the BytesIO buffer and write it to the response.
    epub_file = buffer.getvalue()
    buffer.close()
    response.write(epub_file)
    return response

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password2'])
            login(request, user)
            return redirect(form.cleaned_data['next'])
    else:
        context = {
            'form': RegistrationForm(),
            'next': request.GET.get('next'),
        }
        return render(request, 'courses/register.html', context)

courses/templates/courses/index.html
{% extends "fpp_archive/base.html" %}
{% load staticfiles %}
{% block content %}
{% block conditional-js %}
{% endblock %}
    <section class="browse_subjects">
        <h1> Broswe Subjects </h1>
        <ul>
            <li><a href="#"> God And Country</a></li>
            <li><a href="#"> Communism And Responses</a></li>
            <li><a href="#"> Economy </a></li>
            <li><a href="#"> Education </a></li>
            <li><a href="#"> Globalism </a></li>
            <li><a href="#"> Media Monopoly </a></li>
            <li><a href="#"> Public Policy </a></li>
            <li><a href="#"> Religious Systems </a></li>
            <li><a href="#"> US Military</a></li>
        </ul>
    </section>
    <section class="discover">
        <ul class="grid site-width">
            <li class="wide">
                <div><p>God and Country</p></div>
                <img src="{% static 'fpp_archive/img/courses/1.jpg' %}">
            </li>
            <li class="square">
                <div><p>Globalism</p></div>
                <img src="{% static 'fpp_archive/img/courses/2.jpg' %}">
            </li>
            <li class="square">
                <div><p>Media Monopoly</p></div>
                <img src="{% static 'fpp_archive/img/courses/2.jpg' %}">
            </li>
            <li class="square">
                <div><p>Public Policy</p></div>
                <img src="{% static 'fpp_archive/img/courses/2.jpg' %}">
            </li>
            <li class="square">
                <div><p>Economy</p></div>
                <img src="{% static 'fpp_archive/img/courses/2.jpg' %}">
            </li>
            <li class="square">
                <div><p>Religious Systems</p></div>
                <img src="{% static 'fpp_archive/img/courses/2.jpg' %}">
            </li>
            <li class="wide">
                <div><p>Communism and Responses</p></div>
                <img src="{% static 'fpp_archive/img/courses/1.jpg' %}">
            </li>
            <li class="wide">
                <div><p>Education</p></div>
                <img src="{% static 'fpp_archive/img/courses/1.jpg' %}">
            </li>
            <li class="square">
                <div><p>US Military</p></div>
                <img src="{% static 'fpp_archive/img/courses/2.jpg' %}">
            </li>
        </ul>
    </section>
{% endblock %}

courses/templates/courses/login.html
{% extends "index.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'password_reset' %}">Lost password?</a></p>

{% endblock %}

courses/templates/courses/register.html
{% extends "fpp_archive/base.html" %}


{% block content %}
<div class="narrow-site-width register">
    <form method="post" action="/courses/auth/register/">
        {% csrf_token %}
        {{ form }}
        <input class="btn" type="submit" value="Register" />
        <input id="id_next" type="hidden" name="next" value="{{ next }}" />
    </form>
</div>
{% endblock %}

courses/templates/courses/single.html
{% extends "courses/toc.html" %}

{% block conditional-css %}<!-- Leave Empty -->{% endblock %}
{% block conditional-js %}<!-- Leave Empty -->{% endblock %}

{% block course_downloads %}{% endblock %}

{% block course_content %}
  <section class="lesson_header narrow-site-width">
    <h1>
      <span>Day {{ lesson.day_number }}</span>
      <span class="title">{{ lesson.title }}</span>
    </h1>
    <a href="{{ course.get_absolute_url }}" class="backtoindex">Back to Index</a>
  </section>
  <section class="lesson_content narrow-site-width">
      <hr>
    {{ lesson.content|safe }}
    {% if next %}
    <a href="{{ course.get_absolute_url }}{{ next }}/" class="nextday"><span>Next Day</span> <i class="fa fa-long-arrow-right"></i> </a>
    {% endif %}
    <a href="{{ course.get_absolute_url }}" class="backtoindex">Back to Index</a>
  </section>
  <section class="comments narrow-site-width">
      <hr class="site-width">
    <div id="disqus_thread"></div>
    <script type="text/javascript">
  /* * * CONFIGURATION VARIABLES * * */
  var disqus_shortname = 'fpparchive';

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
  </section>
{% endblock %}

courses/templates/courses/toc.html
{% extends "fpp_archive/base.html" %}
{% load staticfiles %}

{% block conditional-css %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
{% endblock %}

{% block conditional-js %}
<!-- Includes -->
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>

<!-- Scripts -->
<script>
$(function() {
  $( "#accordion" ).accordion();
});
</script>
{% endblock %}

{% block content %}
<section class="course_about site-width">
	<div class="narrow-site-width">
		<h1>{{ course.title }}</h1>
        <hr>
        <h2>{{ course.subtitle }}</h2>
        <hr>
		<p>
            Welcome to the First Principles Press Archive. We invite you to browse our
            collection of documents. As part of your coursework, you will be encouraged
            to use the archive to supplement your learning, and explore topics that
            will illustrate how America came to be and the decisions makers who have
            shaped our nation since.
		</p>
	</div>
	<img src="{% static 'fpp_archive/img/courses/header-tmp.jpg' %}">

  {% block course_downloads %}
    <div class="course_download narrow-site-width">
      <h2>Course Index</h2>
      <a href="#"><div><em>Download E-Book</em> .mobi version</div></a>
      <a href="/courses/epub/{{ course.slug }}/"><div><em>Download E-Book</em> .epub version</div></a>
    </div>
  {% endblock %}
</section>

  {% block course_content %}
  <section class="course_content site-width">
    <ul id="accordion">
      {% for section in lessons %}
      <li>
        <h3>Section {{ section.section_number }} (Day{{ section.total|pluralize }}
          {{ section.start }}{% if not section.solo %}-{{ section.finish }}{% endif %})</h3>
      <ul class="course_days">
      {% for lesson in section.lessons %}
        <!-- Put Link For Individual Page Below -->
        <li><a href="{{ lesson.day_number }}/">
            <em>Day {{ lesson.day_number }}</em> {{ lesson.title }}</a>
        </li>
      {% endfor %}
      </ul>
      </li>
      {% endfor %}
    </ul>
  </section>
  {% endblock %}
{% endblock %}